# Generated by Django 5.2.7 on 2025-12-31 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OyuncuIlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oyun_adi', models.CharField(max_length=100)),
                ('oyuncu_adi', models.CharField(max_length=50)),
                ('rank', models.CharField(max_length=50)),
                ('platform', models.CharField(max_length=30)),
                ('aciklama', models.TextField()),
                ('tarih', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
