# Generated by Django 5.2.7 on 2025-12-21 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyun_degerlendirme', '0002_rename_olusturulma_tarihi_oyundegerlendirme_olusturma_tarihi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oyundegerlendirme',
            name='olusturma_tarihi',
        ),
        migrations.AlterField(
            model_name='oyundegerlendirme',
            name='kullanici',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
